package com.waz.zclient.user.domain.model

data class User(
    val id: String,
    val teamId: String? = null,
    val name: String,
    val handle: String?,
    val email: String?,
    val phone: String?,
    val trackingId: String? = null,
    var picture: String? = null,
    var pictures: List<String>? = null,
    val accentId: Int?,
    val sKey: String? = null,
    val connection: String? = null,
    val connectionTimestamp: Long? = null,
    val connectionMessage: String? = null,
    val conversation: String? = null,
    val relation: String? = null,
    val timestamp: Long? = null,
    val displayName: String? = null,
    val verified: String? = null,
    val deleted: Int,
    val availability: Int? = null,
    val providerId: String? = null,
    val integrationId: String? = null,
    val expiresAt: Int? = null,
    val managedBy: String?,
    val selfPermission: Int? = null,
    val copyPermission: Int? = null,
    val createdBy: String? = null)
